namespace EngineBay.Authentication
{
    public static class EnvironmentVariableConstants
    {
        public const string AUTHENTICATIONSECRET = "AUTHENTICATION_SECRET";

        public const string AUTHENTICATIONAUDIENCE = "AUTHENTICATION_AUDIENCE";

        public const string AUTHENTICATIONISSUER = "AUTHENTICATION_ISSUER";

        public const string AUTHENTICATIONALGORITHM = "AUTHENTICATION_ALGORITHM";

        public const string AUTHENTICATIONVALIDATEAUDIENCE = "AUTHENTICATION_VALIDATE_AUDIENCE";

        public const string AUTHENTICATIONVALIDATEISSUER = "AUTHENTICATION_VALIDATE_ISSUER";

        public const string AUTHENTICATIONVALIDATEEXPIRY = "AUTHENTICATION_VALIDATE_EXPIRY";

        public const string AUTHENTICATIONVALIDATEISSUERSIGNINGKEY = "AUTHENTICATION_VALIDATE_ISSUER_SIGNING_KEY";

        public const string AUTHENTICATIONVALIDATESIGNEDTOKENS = "AUTHENTICATION_VALIDATE_SIGNED_TOKENS";
    }
}